{% set name = "voluptuous" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voluptuous-{{ version }}.tar.gz
  sha256: 006535e22fed944aec17bef6e8725472476194743c87bd233e912eb463f8ff05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - voluptuous
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alecthomas/voluptuous
  summary: Python data validation library
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - tusharmakkar08
    - vamega
    - jan-janssen
