{% set name = "voluptuous" %}
{% set version = "0.12.2" %}
{% set sha256 = "4db1ac5079db9249820d49c891cb4660a6f8cae350491210abce741fabf56513" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - flake8

  run:
    - python

test:
  imports:
    - voluptuous

about:
  home: https://github.com/alecthomas/voluptuous
  license: BSD3
  license_file: COPYING
  summary: Voluptuous is a Python data validation library

extra:
  recipe-maintainers:
    - tusharmakkar08
    - vamega
