{% set name = "voluptuous" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voluptuous-{{ version }}.tar.gz
  sha256: 6ffcab32c4d3230b4d2af3a577c87e1908a714a11f6f95570456b1849b0279aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - voluptuous
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alecthomas/voluptuous
  summary: Python data validation library
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - tusharmakkar08
    - vamega
    - jan-janssen
